context:
  version: "1.1.0"

package:
  name: nitypes
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/n/nitypes/nitypes-${{ version }}.tar.gz
    sha256: f273b5131ef0d5b848c37a0a63452626caf5c2938f7744c324f7991b76fa0b60

build:
  number: 0
  script: ${{ PYTHON }} -m pip install .
  noarch: python

requirements:
  host:
    - python ${{ python_min }}.*
    - poetry-core >=2.1.0,<3.0
    - pip
  run:
    - python >=${{ python_min }}
    - hightime >=0.2.2
    - numpy >=2.1 # python_version >= "3.13" and python_version < "4.0"
    - typing-extensions >=4.13.2

tests:
  - python:
      imports:
        - nitypes
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  homepage: https://github.com/ni/nitypes-python/
  summary: Data types for NI Python APIs
  license_file: LICENSE
  license: MIT
  documentation: https://nitypes.readthedocs.io/

extra:
  recipe-maintainers:
    - carlodri
